syntax = "proto3";

package specedge;

service SpecEdgeService {
    rpc Validate (ValidateRequest) returns (ValidateResponse) {}
    rpc Sync (SyncRequest) returns (SyncResponse) {}
}

message ValidateRequest {
    int32 client_idx = 1;
    int32 req_idx = 2;
    bytes input_ids = 3;
    bytes position_ids = 4;
    bytes cache_seq_indices = 5;
    bytes parent_indices = 6;
    bytes attention_mask = 7;
    bool prefill = 8;
    optional string prefix = 9;
}

message ValidateResponse {
    bytes selection = 1;
    int32 prefill = 2;
    double queue_wait_ms = 3;
    double server_compute_ms = 4;
    double server_response_ms = 5;
    double decode_ms = 6;
    double model_decode_ms = 7;
    double prefill_ms = 8;
    int32 batch_size = 9;
    int32 queue_length = 10;
    double background_arrival_rate = 11;
}

message SyncRequest { }
message SyncResponse { }
