# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: specedge.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0especedge.proto\x12\x08specedge\"\xdb\x01\n\x0fValidateRequest\x12\x12\n\nclient_idx\x18\x01 \x01(\x05\x12\x0f\n\x07req_idx\x18\x02 \x01(\x05\x12\x11\n\tinput_ids\x18\x03 \x01(\x0c\x12\x14\n\x0cposition_ids\x18\x04 \x01(\x0c\x12\x19\n\x11\x63\x61\x63he_seq_indices\x18\x05 \x01(\x0c\x12\x16\n\x0eparent_indices\x18\x06 \x01(\x0c\x12\x16\n\x0e\x61ttention_mask\x18\x07 \x01(\x0c\x12\x0f\n\x07prefill\x18\x08 \x01(\x08\x12\x13\n\x06prefix\x18\t \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_prefix\"\x8f\x02\n\x10ValidateResponse\x12\x11\n\tselection\x18\x01 \x01(\x0c\x12\x0f\n\x07prefill\x18\x02 \x01(\x05\x12\x15\n\rqueue_wait_ms\x18\x03 \x01(\x01\x12\x19\n\x11server_compute_ms\x18\x04 \x01(\x01\x12\x1a\n\x12server_response_ms\x18\x05 \x01(\x01\x12\x11\n\tdecode_ms\x18\x06 \x01(\x01\x12\x17\n\x0fmodel_decode_ms\x18\x07 \x01(\x01\x12\x12\n\nprefill_ms\x18\x08 \x01(\x01\x12\x12\n\nbatch_size\x18\t \x01(\x05\x12\x14\n\x0cqueue_length\x18\n \x01(\x05\x12\x1f\n\x17\x62\x61\x63kground_arrival_rate\x18\x0b \x01(\x01\"\r\n\x0bSyncRequest\"\x0e\n\x0cSyncResponse2\x8f\x01\n\x0fSpecEdgeService\x12\x43\n\x08Validate\x12\x19.specedge.ValidateRequest\x1a\x1a.specedge.ValidateResponse\"\x00\x12\x37\n\x04Sync\x12\x15.specedge.SyncRequest\x1a\x16.specedge.SyncResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'specedge_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VALIDATEREQUEST._serialized_start=29
  _VALIDATEREQUEST._serialized_end=248
  _VALIDATERESPONSE._serialized_start=251
  _VALIDATERESPONSE._serialized_end=522
  _SYNCREQUEST._serialized_start=524
  _SYNCREQUEST._serialized_end=537
  _SYNCRESPONSE._serialized_start=539
  _SYNCRESPONSE._serialized_end=553
  _SPECEDGESERVICE._serialized_start=556
  _SPECEDGESERVICE._serialized_end=699
# @@protoc_insertion_point(module_scope)
