# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import specedge_pb2 as specedge__pb2


class SpecEdgeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Validate = channel.unary_unary(
                '/specedge.SpecEdgeService/Validate',
                request_serializer=specedge__pb2.ValidateRequest.SerializeToString,
                response_deserializer=specedge__pb2.ValidateResponse.FromString,
                )
        self.Sync = channel.unary_unary(
                '/specedge.SpecEdgeService/Sync',
                request_serializer=specedge__pb2.SyncRequest.SerializeToString,
                response_deserializer=specedge__pb2.SyncResponse.FromString,
                )


class SpecEdgeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Validate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpecEdgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Validate': grpc.unary_unary_rpc_method_handler(
                    servicer.Validate,
                    request_deserializer=specedge__pb2.ValidateRequest.FromString,
                    response_serializer=specedge__pb2.ValidateResponse.SerializeToString,
            ),
            'Sync': grpc.unary_unary_rpc_method_handler(
                    servicer.Sync,
                    request_deserializer=specedge__pb2.SyncRequest.FromString,
                    response_serializer=specedge__pb2.SyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'specedge.SpecEdgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SpecEdgeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Validate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/specedge.SpecEdgeService/Validate',
            specedge__pb2.ValidateRequest.SerializeToString,
            specedge__pb2.ValidateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Sync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/specedge.SpecEdgeService/Sync',
            specedge__pb2.SyncRequest.SerializeToString,
            specedge__pb2.SyncResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
